INSERT INTO PLM_CODELOOKUP(CODETYPE,DECODE,ACTIVE,CODEID) VALUES('Exception Type','Qty','Y',1);
INSERT INTO PLM_CODELOOKUP(CODETYPE,DECODE,ACTIVE,CODEID) VALUES('Exception Type','Price','Y',2);
INSERT INTO PLM_CODELOOKUP(CODETYPE,DECODE,ACTIVE,CODEID) VALUES('Exception Type','Cash','Y',3);
INSERT INTO PLM_CODELOOKUP(CODETYPE,DECODE,ACTIVE,CODEID) VALUES('Exception Type','Accrual','Y',4);
INSERT INTO PLM_CODELOOKUP(CODETYPE,DECODE,ACTIVE,CODEID) VALUES('Exception Type','Sec MV','Y',5);